AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Launch Template

Resources:
  baseLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt myCloudWatchProfile.Arn
        InstanceType: t2.micro
        KeyName: nb-stelligent-kp
        SecurityGroupIds:
        - !Ref mySecurityGroup
        UserData: IyEvYmluL2Jhc2gKCmNkIC90bXAKd2dldCBodHRwczovL3MzLmFtYXpvbmF3cy5jb20vYW1hem9uY2xvdWR3YXRjaC1hZ2VudC91YnVudHUvYW1kNjQvbGF0ZXN0L2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50LmRlYgpkcGtnIC1pIC1FIC4vYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQuZGViCnRvdWNoIC9vcHQvYXdzL2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50L2V0Yy9hbWF6b24tY2xvdWR3YXRjaC1hZ2VudC5qc29uCnByaW50ZiAie1xuICBcImFnZW50XCI6IHtcbiAgICBcIm1ldHJpY3NfY29sbGVjdGlvbl9pbnRlcnZhbFwiOiA2MCxcbiAgICBcInJ1bl9hc191c2VyXCI6IFwiY3dhZ2VudFwiXG4gIH0sXG4gIFwibWV0cmljc1wiOiB7XG4gICAgXCJhcHBlbmRfZGltZW5zaW9uc1wiOiB7XG4gICAgICAgIFwiSW5zdGFuY2VJZFwiOiBcIiR7YXdzOkluc3RhbmNlSWR9XCJcbiAgICB9LFxuICAgIFwibWV0cmljc19jb2xsZWN0ZWRcIjoge1xuICAgICAgXCJkaXNrXCI6IHtcbiAgICAgICAgXCJtZWFzdXJlbWVudFwiOiBbXG4gICAgICAgICAgXCJ1c2VkX3BlcmNlbnRcIlxuICAgICAgICBdLFxuICAgICAgICBcIm1ldHJpY3NfY29sbGVjdGlvbl9pbnRlcnZhbFwiOiA2MCxcbiAgICAgICAgXCJyZXNvdXJjZXNcIjogW1xuICAgICAgICAgIFwiL1wiXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIH1cbn1cbiIgPj4gL29wdC9hd3MvYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQvZXRjL2FtYXpvbi1jbG91ZHdhdGNoLWFnZW50Lmpzb24Kc3lzdGVtY3RsIHJlc3RhcnQgYW1hem9uLWNsb3Vkd2F0Y2gtYWdlbnQK
      LaunchTemplateName: nb-baseLaunchTemplate
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
           - "Key": "Name"
             "Value": "nb-baseLaunchTemplate"

  myEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref myUbuntuEC2

  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Allow ssh"
      GroupName: "mySecurityGroup"
      VpcId: vpc-0b92caefc9340c4ff
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0  

  myUbuntuEC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
         LaunchTemplateId: !Ref baseLaunchTemplate
         Version: 1
      ImageId: ami-0efe4f891cb9f7b45
      Tags:
        - Key: "Name"
          Value: "nb-ubuntuEC2"

  myCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Permissions for CloudWatch to log custom metrics from EC2
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy'
      Tags:
        - Key: "Name"
          Value: myCloudWatchRole

  myCloudWatchProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: myCloudWatchProfile
      Roles:
       - !Ref myCloudWatchRole