AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 Launch Template

Resources:
  baseLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        KeyName: nb-stelligent-kp
        SecurityGroupIds:
        - !Ref mySecurityGroup
      LaunchTemplateName: nb-baseLaunchTemplate
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
           - "Key": "Name"
             "Value": "nb-baseLaunchTemplate"

  myEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref myUbuntuEC2

  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Allow ssh"
      GroupName: "mySecurityGroup"
      VpcId: vpc-0b92caefc9340c4ff
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0  

  myUbuntuEC2:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
         LaunchTemplateId: !Ref baseLaunchTemplate
         Version: 1
      ImageId: ami-0efe4f891cb9f7b45
      Tags:
        - Key: "Name"
          Value: "nb-ubuntuEC2"