AWSTemplateFormatVersion: "2010-09-09"
Description: AWS S3 User
Resources:
  myVPC2:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: "10.10.0.0/16"
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      Tags:
      - Key: Name
        Value: nbaker-stelligent-lab-4
      - Key: user
        Value: nbaker-stelligent
      - Key: stelligent-u-lesson
        Value: "4.1"
      - Key: stelligent-u-lab
        Value: "4.1.2"
  peerMainVPC:
    Type: AWS::EC2::VPCPeeringConnection
    Properties: 
      PeerVpcId: !ImportValue myVPC
      VpcId: !Ref myVPC2
  myPeerACL:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: !Ref myVPC2
  peerInboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: myPeerACL
       RuleNumber: 100
       Protocol: -1
       RuleAction: allow
       CidrBlock: 10.0.0.0/16
       PortRange:
         From: 0
         To: 0
  peerOutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId:
         Ref: myPeerACL
       RuleNumber: 200
       Protocol: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0
  myPeerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: myVPC2
      CidrBlock: 10.10.1.0/24
      AvailabilityZone: "us-east-1a"
  myPeerEC2:  
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      KeyName: nb-stelligent-kp
      SubnetId: !Ref myPeerSubnet
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 25
  peerRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: myVPC2
  attachRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !Ref peerRouteTable
      SubnetId: !Ref myPeerSubnet
  peerRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: peerRouteTable
      DestinationCidrBlock: 10.0.0.0/16
      VpcPeeringConnectionId: !Ref peerMainVPC