AWSTemplateFormatVersion: "2010-09-09"
Description: AWS EC2 Instance
Resources:
  myEC2:  
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      KeyName: nb-stelligent-kp
      SubnetId: !ImportValue mySubnet
      SecurityGroupIds: 
        - !Ref mySecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 25
  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "Allow ssh"
      GroupName: "mySecurityGroup"
      VpcId: !ImportValue myVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp
        FromPort: -1
        ToPort: -1
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref myEC2
