AWSTemplateFormatVersion: "2010-09-09"
Description: AWS S3 User
Parameters:
  UserName:
    Description: User Name
    Type: String
    Default: "SpecialS3ReadOnlyUser"

Resources:
  SpecialS3ReadOnlyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Groups:
      - !Ref SpecialS3ReadOnlyGroup

  SpecialS3ReadOnlyGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: SpecialS3ReadOnlyGroup
  
  SpecialS3ReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SpecialS3ReadOnlyPolicy
      Groups:
      - !Ref SpecialS3ReadOnlyGroup
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: All 
          Effect: Allow
          Action:
          - s3:GetBucketPolicyStatus
          - s3:GetBucketPublicAccessBlock
          - s3:GetLifecycleConfiguration
          - s3:GetBucketTagging
          - s3:GetInventoryConfiguration
          - s3:GetBucketWebsite
          - s3:GetBucketLogging
          - s3:GetBucketVersioning
          - s3:GetBucketAcl
          - s3:GetBucketNotification
          - s3:GetBucketPolicy
          - s3:GetBucketObjectLockConfiguration
          - s3:GetEncryptionConfiguration
          - s3:GetIntelligentTieringConfiguration
          - s3:GetBucketRequestPayment
          - s3:GetBucketCORS
          - s3:GetMetricsConfiguration
          - s3:GetBucketOwnershipControls
          Resource: arn:aws:s3:::*
        - Sid: Objects
          Effect: Allow
          Action:
          - s3:GetObjectVersionTorrent
          - s3:GetObjectAcl
          - s3:GetObject
          - s3:GetObjectTorrent
          - s3:GetObjectRetention
          - s3:GetObjectVersionTagging
          - s3:GetObjectVersionAcl
          - s3:GetObjectTagging
          - s3:GetObjectVersion
          Resource: arn:aws:s3:::*/*

Outputs:
  SpecialS3Group:
    Description: The S3 Group ARN
    Export:
      Name: SpecialS3ReadOnlyGroup
    Value: !Ref SpecialS3ReadOnlyGroup
