AWSTemplateFormatVersion: "2010-09-09"
Description: S3 resource creation
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: nbaker-labs-bucket
