AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketNameParameter:
    Type: String
  ghToken:
    Type: String
    NoEcho: true
  ghOwner:
    Type: String
  ghRepo:
    Type: String
  ghBranch:
    Type: String
  appStackName:
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter
    DeletionPolicy: Delete
  appIAMRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: 
              - codepipeline.amazonaws.com
              - codebuild.amazonaws.com
              - cloudformation.amazonaws.com
          Action: sts:AssumeRole
  appCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      ArtifactStore: 
        Location: !Ref S3Bucket
        Type: S3
      RoleArn: !GetAtt appIAMRole.Arn
      Stages: 
        - Name: Deploy
          Actions: 
            - Name: deploy_a
              ActionTypeId: 
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration: 
                ActionMode: "CHANGE_SET_REPLACE"
                StackName: !Ref appStackName
                RoleArn: !GetAtt appIAMRole.Arn
                ChangeSetName: !Ref appStackName
                Capabilities:
                  CAPABILITY_IAM
                TemplatePath: SourceOutput::12-codepipeline/lab_12_2_1.yaml
              InputArtifacts: 
                - Name: SourceOutput
              RunOrder: 1
        - Name: Approval
          ActionTypeId: 
            Category: Approval
            Owner: AWS
            Provider: Manual
            Version: 1
          RunOrder: 2
        - Name: deploy_b
          ActionTypeId: 
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration: 
            ActionMode: "CHANGE_SET_EXECUTE"
            StackName: !Ref appStackName
            RoleArn: !GetAtt appIAMRole.Arn
            Capabilities:
              CAPABILITY_IAM
            ChangeSetName:
              !Ref appStackName
            TemplatePath: SourceOutput::12-codepipeline/lab_12_2_1.yaml
          InputArtifacts: 
            - Name: SourceOutput
          RunOrder: 3