AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: myLogGroup

  myS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stelligent-u-nbaker
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  
  cloudTrailLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AssumeRole1
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: 'cloudtrail-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: !GetAtt 'myLogGroup.Arn'

  myTrailBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref myS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:GetBucketAcl'
          Resource: !Sub 'arn:aws:s3:::${myS3Bucket}'
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 's3:PutObject'
          Resource: !Sub 'arn:aws:s3:::${myS3Bucket}/AWSLogs/${AWS::AccountId}/*'
          Condition:
            StringEquals:
              's3:x-amz-acl': 'bucket-owner-full-control'

  myCloudTrail:
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: !Ref myS3Bucket
      CloudWatchLogsLogGroupArn: !GetAtt 'myLogGroup.Arn'
      CloudWatchLogsRoleArn: !GetAtt 'cloudTrailLogsRole.Arn'
      SnsTopicName: !GetAtt 'myTrailTopic.TopicName'

  myTrailTopic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  myTrailTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AWSCloudTrailSNSPolicy
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Resource: !Ref myTrailTopic
          Action: 'sns:Publish'
      Topics:
      - !Ref myTrailTopic
  mySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: myemail@stelligent.com
      Protocol: email
      TopicArn: !Ref 'myTrailTopic'