AWSTemplateFormatVersion: "2010-09-09"
Description: AWS S3 User
Resources:
  CustomIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide readonly access to IAM
      Policies:
        - PolicyName: EmbeddedInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                - "iam:GenerateCredentialReport"
                - "iam:GenerateServiceLastAccessedDetails"
                - "iam:Get*"
                - "iam:List*"
                - "iam:SimulateCustomPolicy"
                - "iam:SimulatePrincipalPolicy"       
                Resource: '*'      
      RoleName: CustomIAMRole
      
  # DynamoDBMangedPolicy:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties: 
  #     Description: Managed Policy to attach to MyTestRole Role
  #     ManagedPolicyName: DynamoDBAccessPolicyForLambda
  #     Path: /
  #     PolicyDocument: 
  #       Version: "2012-10-17"
  #       Statement:
  #         - Effect: Allow
  #           Action:
  #             - 'dynamodb:Query'
  #             - 'dynamodb:Scan'
  #           Resource: '*'
  #     Roles: 
  #       - !Ref MyTestRole