AWSTemplateFormatVersion: "2010-09-09"
Description: AWS S3 User
Resources:
  CustomIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide readonly access to IAM
      RoleName: CustomIAMRole

  CustomIAMRole2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - 'sts:AssumeRole'
      Description: Role to provide readonly access to IAM
      RoleName: CustomIAMRole2

  CustomIAMReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
      - !Ref CustomIAMRole
      - !Ref CustomIAMRole2
      ManagedPolicyName: CustomIAMReadOnlyPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
            - "iam:GenerateCredentialReport"
            - "iam:GenerateServiceLastAccessedDetails"
            - "iam:Get*"
            - "iam:List*"
            - "iam:SimulateCustomPolicy"
            - "iam:SimulatePrincipalPolicy"       
            Resource: '*'
